### ISSUE TITLE
PnP management shell ID doesn't work anymore

### ISSUE THREAD

**Issue by shrx** [codeforkjeff/teams-chats-export#2]
Discussion about the issue:

https://old.reddit.com/r/sysadmin/comments/1fe9af9/microsofts_latest_surprise_entra_id_app/

https://github.com/pnp/blog/issues/1909

announcement: https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/

**Comment by codeforkjeff** [comment]
I noticed that it stopped working two days ago but hadn't seen that announcement. Thank you for linking to it!

I think if you create a new Entra ID app and replace the value of the "pnp_management_shell_client_id" variable in `teams_chats_export.py` with your app id, it should work.

I need to try that myself and if it works, I'll create a more user-friendly way to set that variable.
